### ISSUE TITLE
Capture stdout and stderr in test_docker test case

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/std#198]
**Problem:**

The test case `tests/test_in_docker::test_docker` starts a docker container to run the std tests in that container. The `subprocess.run()` however doesn't capture stdout or stderr. This way it's impossible determine the root cause of the problem in case the `docker exec` command fails. 

**Tasks:**

- [ ] Ensure that if the `docker exec` fails, stdout and stderr are reported to the user.
- [ ] Resolve the same issue in the `docker_container` fixture as well (see: conftest.py)

**Comment by arnaudsjs** [comment]
According to the Jenkins logs, this failure was due to:

```
Error getting v2 registry: Get https://registry-1.docker.io/v2/: EOF
``` 

I agree with @edvgui  that there is no bug in the test code which causes logs not to be shown to the user. Probably this line was never sent to stdout or stderr.

**Comment by edvgui** [comment]
We *might* have more chance next time if we use the docker sdk: https://github.com/inmanta/std/issues/200  (if the docker cli fails to print something it won't affect us at least)
