### ISSUE TITLE
Templates and dict do not play well together

### ISSUE THREAD

**Issue by bartv** [inmanta/std#20]
In a template it should be possible to iterate over the key,values or todo key lookup. Both currently fail due to the proxies not implementing the correct protocols.

- A key lookup produces ``Exception in plugin std::template caused by AttributeError: 'Dict' object has no attribute 'get_attribute'``
- Iteration produces: ``Exception in plugin std::template caused by 'inmanta_plugins.std.SequenceProxy object' has no attribute 'items'``

**Comment by bartv** [comment]
This one might already be fixed

**Comment by sanderr** [comment]
- What currently works:
```jinja
{% for x in mydict %}
    key: {{ x }}
{% endfor %}
```

- What doesn't work:
  - `{{ mydict["mykey"] }}`
  - `{{ mydict.get_attribute("mykey") }}`


Should all of these be supported?

**Comment by bartv** [comment]
I do not see why get_attribute should be supported. However, it would be good that you can use them as you would use a real python dict in jinja. Maybe a simple workaround is to copy the inmanta dict to a python dict? They are readonly anyway.
