### ISSUE TITLE
Undefined should not be passed to plugin

### ISSUE THREAD

**Issue by sanderr** [inmanta/std#213]
When a jinja template contains an undefined variable that gets passed to a plugin, core converts this `jinja2.runtime.Undefined` value to `SequenceProxy` because it has a `__len__` attribute. This can lead to very difficult to understand error messages, especially when the plugin in question is `std::get_env`. This plugin checks `name in os.environ` which leads to a type error because `name` is a `SequenceProxy` while a string is expected.
The expected behavior in would be to prevent any jinja internal objects to pass through the plugin domain. The jinja "is defined" should still work -> create a test case.

A reproductive project:
`main.cf`:
```
import mymod
```

`libs/mymod/model/_init.cf`:
```
std::print(std::template("./my_template.j2"))
```

`libs/mymod/plugins/__init__.py`:
```
from inmanta.plugins import plugin


@plugin
def get_type(obj: "any") -> "string":
    return str(type(obj))
```

`libs/mymod/templates/my_template.j2`:
```
{{ undefined_var | my_mod.get_type }}
```

**Comment by wouterdb** [comment]
This might be related to jinja is defined

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/std/213?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
