### ISSUE TITLE
Add ResourceSet entity

### ISSUE THREAD

**Issue by arnaudsjs** [inmanta/std#349]
Tasks:

- [x] Add the `ResourceSet` entity to the std module

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/std/349?planning-poker) with ZenHub @andraskvr @arnaudsjs @FloLey @Hugo-Inmanta @sanderr
