### ISSUE TITLE
drop final number types

### ISSUE THREAD

**Issue by sanderr** [inmanta/std#548]
There are some remaining uses of the number type:
- a version number -> could be made `float`
- `MutableNumber` -> replace with `MutableFloat` and `MutableInt`
- typedefs for positive/negative float/int -> replace with respective counterparts

**Comment by wouterdb** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/core-5a7c152b04a1652024289b7b/issues/inmanta/std/548?planning-poker) with Zenhub @arnaudsjs @hlloreda @Hugo-Inmanta @jptrindade
